apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: nginx-deployment
      env: nginx-env
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: nginx-deployment
        env: nginx-env
    spec:
      containers:
        - image: nginx:latest
          name: nginx-deployment
          ports:
            - containerPort: 80
